### PR TITLE
Create a Plex Cleaner Dockerfile

### PR DESCRIPTION
**Pull request by NitriKx**

### CODE REVIEW

**Comment by jokerigno** [comment]
That will be great!

**Comment by ngovil21** [comment]
This looks good, but is there anything that requires it to be in the github here? Would it be possible to create a docker hub and then I can link to it in the README. I would prefer that because I don't want to in charge of updating it.

**Comment by NitriKx** [comment]
Yep no problem, I'm going create it.

**Comment by LSL1337** [comment]
wow, plex cleaner docker. it would be awesome. looking forward to it

**Comment by NitriKx** [comment]
I created the repo: https://github.com/NitriKx/docker-Plex-Cleaner. The CI is not finished but the latest version is pushed

**Comment by NitriKx** [comment]
I've removed the Docker related items, and updated the README to mention the Dockerized version

**Comment by ngovil21** [comment]
Thanks for doing that. One more things before merge, can you pass in variables in the docker script? It's very important to me that people run the script with `--test` for their first run. Don't want people to get upset that the script blew through their library by being improperly configured. 

Please add that in your README.MD if possible. If you can't figure it out, I will add the test variable to the sample config.

Also instead of running `PlexCleaner.py --dump` use `cp /app/Cleaner.conf.default /config/Cleaner.conf`

Thank you for creating this.

**Comment by NitriKx** [comment]
Ok I will make the docker working with the following syntax : 
```
docker run -ti -v /path/to/config/folder nitrikx/plex-cleaner --test --otherparams
```
At the end the following will be called: 
```
python /app/PlexCleaner.py --config "/config/Cleaner.conf" --test --otherparams
```
I'm also changing the init with `cp`.
Thanks for those precisions.

**Comment by NitriKx** [comment]
I've made the changes. 
Thanks for building this amazing script!

**Pull request merged**
